name: macOS Hardware Info

on: workflow_dispatch

jobs:
  hardware:
    runs-on: macos-latest
    steps:
      - name: Install fastfetch
        run: brew install fastfetch
      
      - name: Show system info
        run: fastfetch
